cmake_minimum_required(VERSION 3.14 FATAL_ERROR)

# GRPC_DIR
if (NOT GRPC_SOURCE_DIR)
    set(GRPC_SOURCE_DIR ${THIRD_PARTY_SOURCE_DIR}/grpc)
endif ()
message(STATUS "GRPC_SOURCE_DIR=${GRPC_SOURCE_DIR}")

if (NOT GRPC_BINARY_DIR)
    set(GRPC_BINARY_DIR ${THIRD_PARTY_BINARY_DIR}/grpc)
endif ()
message(STATUS "GRPC_BINARY_DIR=${GRPC_BINARY_DIR}")


find_path(GRPC_INCLUDE "grpcpp/grpcpp.h" HINTS ${GRPC_SOURCE_DIR} PATH_SUFFIXES "include" NO_DEFAULT_PATH)
message(STATUS "GRPC_INCLUDE=${GRPC_INCLUDE}")


set(GRPC_LIBRARIES)
foreach(COMPONENT ${GRPC_FIND_COMPONENTS})
    set(GRPC_COMPONENT_LIBRARY ${LIBRARY_PREFIX}${COMPONENT}${LIBRARY_SUFIX})
    message(STATUS "GRPC_COMPONENT_LIBRARY=${GRPC_COMPONENT_LIBRARY}")
    find_library(GRPC_LIB NAMES ${GRPC_COMPONENT_LIBRARY} HINTS ${GRPC_BINARY_DIR} PATH_SUFFIXES lib PATHS ${GRPC_BINARY_DIR})
    list(APPEND GRPC_LIBRARIES ${GRPC_LIB})
    unset(GRPC_LIB CACHE)
endforeach()



include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(GRPC REQUIRED_VARS
        GRPC_LIBRARIES
        GRPC_INCLUDE
        )
